### ISSUE TITLE
AttributeError: type object 'object' has no attribute '__getattr__'

### ISSUE THREAD

**Issue by jjqtony** [wentaozhu/DeepLung#11]
When I run run_train.sh, get the following error:
Traceback (most recent call last):
  File "main.py", line 393, in <module>
    main()
  File "main.py", line 210, in main
    train(train_loader, net, loss, epoch, optimizer, get_lr, args.save_freq, save_dir)
  File "main.py", line 238, in train
    state_dict = net.module.state_dict()
  File "/home/jin/anaconda2/envs/lung/lib/python2.7/site-packages/torch/nn/modules/module.py", line 237, in __getattr__
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'

How to fix it?

**Comment by jjqtony** [comment]
I have fixed it by upgrading pytorch to 0.1.11.

**Comment by wentaozhu** [comment]
Glad to hear about it! Thank you very much for your interest on our work!
