### ISSUE TITLE
Preprocessing

### ISSUE THREAD

**Issue by mike1123412** [wentaozhu/DeepLung#138]
Dear Wentao,
I have recreated the required environment, but when I start the preprocessing, it freezes at 1.3.6.1.4.1.14519.5.2.1.6279.6001.430109407146633213496148200410.
Then I get the following errors when I try to stop the preprocessing:
`Process PoolWorker-6:
Process PoolWorker-12:
Process PoolWorker-13:
Process PoolWorker-10:
Process PoolWorker-2:
Process PoolWorker-7:
Process PoolWorker-3:
Process PoolWorker-1:
Process PoolWorker-8:
Process PoolWorker-14:
Process PoolWorker-9:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Process PoolWorker-5:
Traceback (most recent call last):
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self.run()
    self.run()
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    self.run()
    self.run()
    self.run()
    self.run()
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
    self.run()
    self.run()
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    self.run()
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    self.run()
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
    task = get()
    task = get()
    task = get()
    task = get()
    task = get()
    task = get()
    task = get()
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/queues.py", line 374, in get
    task = get()
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/queues.py", line 374, in get
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/queues.py", line 374, in get
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/queues.py", line 374, in get
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/queues.py", line 374, in get
    task = get()
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/queues.py", line 374, in get
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/queues.py", line 374, in get
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/queues.py", line 376, in get
    task = get()
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/queues.py", line 374, in get
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/queues.py", line 374, in get
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/queues.py", line 374, in get
    task = get()
  File "/home/mike/anaconda3/envs/DeepLung/lib/python2.7/multiprocessing/queues.py", line 374, in get
    racquire()
    racquire()
    racquire()
    racquire()
    racquire()
    racquire()
    racquire()
    racquire()
    return recv()
    racquire()
    racquire()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
    racquire()
KeyboardInterrupt
KeyboardInterrupt
`

**Comment by mike1123412** [comment]
The problem occurred due to insufficient amount of RAM.
