### ISSUE TITLE
noduleCADEvaluationLUNA16compare error

### ISSUE THREAD

**Issue by AlejandraM97** [wentaozhu/DeepLung#143]
Hello Mr. @wentaozhu, on the ReadMe you say "You can directly run noduleCADEvaluationLUNA16.py, and get the performance in the paper." but when I try to directly run the .py, there's an error and I have not idea why it is, could you help me? Am I doing something wrong?

This is the error:

\DeepLung>python evaluationScript\noduleCADEvaluationLUNA16compare.py
Anotations file path:
C:\Users\aleja\Documents\DeepLung\evaluationScript\annotations\newannotations.csv
C:\Users\aleja\Documents\DeepLung\evaluationScript\annotations\newannotations_excluded.csv
C:\Users\aleja\Documents\DeepLung\evaluationScript\annotations\newseriesuids.csv
Traceback (most recent call last):
  File "evaluationScript\noduleCADEvaluationLUNA16compare.py", line 530, in <module>
    (noduleCADEvaluation(annotations_filename,annotations_excluded_filename,seriesuids_filename,results_filename,'./', vis=True, delimiter='\t', clr = 'r', cap='3DDPN26FasterR-CNN'))
  File "evaluationScript\noduleCADEvaluationLUNA16compare.py", line 509, in noduleCADEvaluation
    (allNodules, seriesUIDs) = collect(annotations_filename, annotations_excluded_filename, seriesuids_filename)
  File "evaluationScript\noduleCADEvaluationLUNA16compare.py", line 484, in collect
    annotations          = csvTools.readCSV(annotations_filename)
  File "C:\xxxx\xxxx\xxxx\DeepLung\evaluationScript\tools\csvTools.py", line 12, in readCSV
    for line in csvreader:
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)

What is the './' on the function "noduleCADEvaluation" for?

Thank you in advantage, I'll wait for your answer

**Comment by wentaozhu** [comment]
It is csv error. Maybe you can try to run on a linux environment because the csv is different on windows. Thank you!

**Comment by AlejandraM97** [comment]
Thank you very much for your help. In fact, I tried to read the CSV in a normal way, without binary files, just "r". But i have another question if you're okay with it.

When I'm trying to run "noduleCADEvaluationLUNA16.py", there's a part on computeFROC def, when you make a for and indexed a local FROCGT or FROCProb if there's a false on the "exclude list"

for i in range(len(excludeList)):
        if excludeList[i] == False:
            FROCGTList_local.append(FROCGTList[i])
            FROCProbList_local.append(FROCProbList[i])

But when I try it, it just has True responses, so there's no way on how to calculate the roc_curve and this is the error:

Traceback (most recent call last):
  File "evaluationScript\noduleCADEvaluationLUNA16.py", line 531, in <module>
    noduleCADEvaluation(annotations_filename,annotations_excluded_filename,seriesuids_filename,results_filename,'./')
  File "evaluationScript\noduleCADEvaluationLUNA16.py", line 523, in noduleCADEvaluation
    numberOfBootstrapSamples=bNumberOfBootstrapSamples, confidence=bConfidence)
  File "evaluationScript\noduleCADEvaluationLUNA16.py", line 359, in evaluateCAD
    fps, sens, thresholds = computeFROC(FROCGTList,FROCProbList,len(seriesUIDs),excludeList)
  File "evaluationScript\noduleCADEvaluationLUNA16.py", line 144, in computeFROC
    fpr, tpr, thresholds = skl_metrics.roc_curve(FROCGTList_local, FROCProbList_local)
  File "C:\Users\aleja\anaconda3\envs\pytorch_exp\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\aleja\anaconda3\envs\pytorch_exp\lib\site-packages\sklearn\metrics\_ranking.py", line 914, in roc_curve
    y_true, y_score, pos_label=pos_label, sample_weight=sample_weight)
  File "C:\Users\aleja\anaconda3\envs\pytorch_exp\lib\site-packages\sklearn\metrics\_ranking.py", line 702, in _binary_clf_curve
    pos_label = _check_pos_label_consistency(pos_label, y_true)
  File "C:\Users\aleja\anaconda3\envs\pytorch_exp\lib\site-packages\sklearn\metrics\_base.py", line 244, in _check_pos_label_consistency
    f"y_true takes value in {{{classes_repr}}} and pos_label is not "
ValueError: y_true takes value in {} and pos_label is not specified: either make y_true take value in {0, 1} or {-1, 1} or pass pos_label explicitly.

Could you help me about it?

**Comment by AlejandraM97** [comment]
Traceback (most recent call last):
  File "evaluationScript/noduleCADEvaluationLUNA16.py", line 522, in <module>
    noduleCADEvaluation(annotations_filename,annotations_excluded_filename,seriesuids_filename,results_filename,'./')
  File "evaluationScript/noduleCADEvaluationLUNA16.py", line 514, in noduleCADEvaluation
    numberOfBootstrapSamples=bNumberOfBootstrapSamples, confidence=bConfidence)
  File "evaluationScript/noduleCADEvaluationLUNA16.py", line 350, in evaluateCAD
    fps, sens, thresholds = computeFROC(FROCGTList,FROCProbList,len(seriesUIDs),excludeList)
  File "evaluationScript/noduleCADEvaluationLUNA16.py", line 137, in computeFROC
    fpr, tpr, thresholds = skl_metrics.roc_curve(FROCGTList_local, FROCProbList_local)
  File "/home/arumota/anaconda3/envs/pytorch_exp/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/arumota/anaconda3/envs/pytorch_exp/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 914, in roc_curve
    y_true, y_score, pos_label=pos_label, sample_weight=sample_weight)
  File "/home/arumota/anaconda3/envs/pytorch_exp/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 702, in _binary_clf_curve
    pos_label = _check_pos_label_consistency(pos_label, y_true)
  File "/home/arumota/anaconda3/envs/pytorch_exp/lib/python3.7/site-packages/sklearn/metrics/_base.py", line 244, in _check_pos_label_consistency
    f"y_true takes value in {{{classes_repr}}} and pos_label is not "
ValueError: y_true takes value in {} and pos_label is not specified: either make y_true take value in {0, 1} or {-1, 1} or pass pos_label explicitly.

In fact, I also tried on a Linux distro, maybe thinking it was about the lecture of "evaluationScript/annotations/newannotations.csv", but the same error happened

**Comment by wentaozhu** [comment]
Yes. Try the linux and re-download all the files.

**Comment by BelieferQAQ** [comment]
> Thank you very much for your help. In fact, I tried to read the CSV in a normal way, without binary files, just "r". But i have another question if you're okay with it.
> 
> When I'm trying to run "noduleCADEvaluationLUNA16.py", there's a part on computeFROC def, when you make a for and indexed a local FROCGT or FROCProb if there's a false on the "exclude list"
> 
> for i in range(len(excludeList)): if excludeList[i] == False: FROCGTList_local.append(FROCGTList[i]) FROCProbList_local.append(FROCProbList[i])
> 
> But when I try it, it just has True responses, so there's no way on how to calculate the roc_curve and this is the error:
> 
> Traceback (most recent call last): File "evaluationScript\noduleCADEvaluationLUNA16.py", line 531, in noduleCADEvaluation(annotations_filename,annotations_excluded_filename,seriesuids_filename,results_filename,'./') File "evaluationScript\noduleCADEvaluationLUNA16.py", line 523, in noduleCADEvaluation numberOfBootstrapSamples=bNumberOfBootstrapSamples, confidence=bConfidence) File "evaluationScript\noduleCADEvaluationLUNA16.py", line 359, in evaluateCAD fps, sens, thresholds = computeFROC(FROCGTList,FROCProbList,len(seriesUIDs),excludeList) File "evaluationScript\noduleCADEvaluationLUNA16.py", line 144, in computeFROC fpr, tpr, thresholds = skl_metrics.roc_curve(FROCGTList_local, FROCProbList_local) File "C:\Users\aleja\anaconda3\envs\pytorch_exp\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f return f(*args, **kwargs) File "C:\Users\aleja\anaconda3\envs\pytorch_exp\lib\site-packages\sklearn\metrics_ranking.py", line 914, in roc_curve y_true, y_score, pos_label=pos_label, sample_weight=sample_weight) File "C:\Users\aleja\anaconda3\envs\pytorch_exp\lib\site-packages\sklearn\metrics_ranking.py", line 702, in _binary_clf_curve pos_label = _check_pos_label_consistency(pos_label, y_true) File "C:\Users\aleja\anaconda3\envs\pytorch_exp\lib\site-packages\sklearn\metrics_base.py", line 244, in _check_pos_label_consistency f"y_true takes value in {{{classes_repr}}} and pos_label is not " ValueError: y_true takes value in {} and pos_label is not specified: either make y_true take value in {0, 1} or {-1, 1} or pass pos_label explicitly.
> 
> Could you help me about it?

could you tell me how to solve this problem? thank you
