### ISSUE TITLE
The problem about ./detector/main.py

### ISSUE THREAD

**Issue by anruoxi123** [wentaozhu/DeepLung#34]
@wentaozhu 

When I ran./detector/main.py, the following error was reported:
Traceback (most recent call last):
  File "main.py", line 390, in <module>
    main()
  File "main.py", line 70, in main
    model = import_module(args.model)
  File "/home/user/anaconda3/envs/mhqtf/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
ImportError: No module named 'base'

My cudn version is 7.5, is it related to the cudn version？

**Comment by wentaozhu** [comment]
I used Python 2. Maybe you can have a try.

**Comment by anruoxi123** [comment]
Ok, thanks for your advice！

**Comment by anruoxi123** [comment]
@wentaozhu 
Dear teacher,
    When I replaced python2.7 and ran./detector/main.py, the following error was reported:
    Traceback (most recent call last):
  File "main.py", line 391, in <module>
    main()
  File "main.py", line 71, in main
    config, net, loss, get_pbb = model.get_model()
AttributeError: 'module' object has no attribute 'get_model'
Is the problem caused by a build error in the running environment？

**Comment by wentaozhu** [comment]
You should run the ./run_training.sh file
