### ISSUE TITLE
problem about evaluationScript

### ISSUE THREAD

**Issue by jehovahxu** [wentaozhu/DeepLung#42]
how can i get a csv file like **3DRes18FasterR-CNN.csv**

**Comment by wentaozhu** [comment]
You need to run 10 times. Use 1 fold as test, and other 9 folds as training. After that, concatenate 10 csv files.

**Comment by jehovahxu** [comment]
> You need to run 10 times. Use 1 fold as test, and other 9 folds as training. After that, concatenate 10 csv files.

```
annotations_filename = './annotations/annotations.csv'  # path for ground truth annotations for the fold
annotations_excluded_filename = './annotations/annotations_excluded.csv'  # path for excluded annotations for the fold
seriesuids_filename = './annotations/seriesuids.csv'  # path for seriesuid for the fold
results_path = '/home/kejia/PycharmProjects/DeepLung-master/detector/results/res18/retrft969/val' #val'  # val' ft96'+'/val'#
sideinfopath = '/media/jehovah/Work/data/LUNA/propocess/subset9/'  # subset'+str(fold)+'/'  +str(fold)
datapath = '/media/jehovah/Work/data/LUNA/rowfile/subset9/'  # subset'+str(fold)+'/'
``` 
I can only run the frocwrtdetpepchluna16.py  with such path . when i modified the **subset9** to **subset0**
the error occur
`Traceback (most recent call last):
  File "/home/kejia/PycharmProjects/DeepLung-master/evaluationScript/frocwrtdetpepchluna16.py", line 165, in <module>
    getcsv(detp, eps)
  File "/home/kejia/PycharmProjects/DeepLung-master/evaluationScript/frocwrtdetpepchluna16.py", line 155, in getcsv
    predannolist = p.map(functools.partial(convertcsv, bboxpath=bboxpath, detp=detpthresh), fnamelist)
  File "/home/kejia/anaconda2/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/kejia/anaconda2/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
IOError: [Errno 2] No such file or directory: '/media/jehovah/Work/data/LUNA/rowfile/subset0/1.3.6.1.4.1.14519.5.2.1.6279.6001.300392272203629213913702120739.mhd'
ep 1 detp -1.5
88
`

**Comment by jehovahxu** [comment]
And i where can i get the output csv file about frocwrtdetpepchluna16.py .  is that under every val fold ?

**Comment by wentaozhu** [comment]
For each fold, you need to use the fold's annotation to run the frocwrtdetpepchluna16.py 

The froc w.r.t. detection probability and epoch on LUNA16 (frocwrtdetpepchluna16.py ) will tell you which detection probability and epoch is the best. Then you can collect the csv files of the epoch in the detection results folder. You are getting the csv file for the fold.
