### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by Shrutika994** [wentaozhu/DeepLung#95]
Hello. This error keeps occurring while i try to train using the source code. So far i figured out Python 3 does not auto convert floats to integers in division unless you use //. But not sure do i have change the whole code or what.

Traceback (most recent call last):
  File "main.py", line 387, in <module>
    main()
  File "main.py", line 163, in main
    pin_memory=True)
  File "/home/shru/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/home/shru/anaconda3/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 92, in __init__
    if not isinstance(self.num_samples, int) or self.num_samples <= 0:
  File "/home/shru/anaconda3/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 100, in num_samples
    return len(self.data_source)
TypeError: 'float' object cannot be interpreted as an integer

**Comment by wentaozhu** [comment]
Thank you so much for your contribution! I think if there is no the error for division, you don’t need to modify it.
发自网易邮箱大师
On 10/22/2019 14:18, Shrutika994 wrote: Hello. This error keeps occurring while i try to train using the source code. So far i figured out Python 3 does not auto convert floats to integers in division unless you use //. But not sure do i have change the whole code or what.
Traceback (most recent call last):
File "main.py", line 387, in 
main()
File "main.py", line 163, in main
pin_memory=True)
File "/home/shru/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 213, in init
sampler = RandomSampler(dataset)
File "/home/shru/anaconda3/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 92, in init
if not isinstance(self.num_samples, int) or self.num_samples <= 0:
File "/home/shru/anaconda3/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 100, in num_samples
return len(self.data_source)
TypeError: 'float' object cannot be interpreted as an integer

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/wentaozhu/DeepLung/issues/95?email_source=notifications\u0026email_token=ACMYWLI6ABNNI47PMTVLW6DQP2LM5A5CNFSM4JDLCAM2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HTM3X4Q",
"url": "https://github.com/wentaozhu/DeepLung/issues/95?email_source=notifications\u0026email_token=ACMYWLI6ABNNI47PMTVLW6DQP2LM5A5CNFSM4JDLCAM2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HTM3X4Q",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Alexander0211** [comment]
using gpu 1,2,3
trainfilelist= 800
800
Traceback (most recent call last):
  File "main.py", line 387, in <module>
    main()
  File "main.py", line 163, in main
    pin_memory = True)
  File "/home/share/software/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/home/share/software/anaconda3/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 92, in __init__
    if not isinstance(self.num_samples, int) or self.num_samples <= 0:
  File "/home/share/software/anaconda3/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 100, in num_samples
    return len(self.data_source)
TypeError: 'float' object cannot be interpreted as an integer
@Shrutika994 
 i meet the same error as you, I try to replace all “ /"  with “ //" for Python3. But it can not work. i want know how to solve this question. Hope you can help. Thanks.

**Comment by wentaozhu** [comment]
I am outside and I remember there are previous issues about this and the issue can be fixed. Please check previous reported issues.
