### ISSUE TITLE
some error about 'forcwrtdetpepchluna16.py'

### ISSUE THREAD

**Issue by hengliang8** [wentaozhu/DeepLung#99]
Traceback (most recent call last):
  File "/media/omnisky/1F4F46694A801839/zhl/DeepLung-master/evaluationScript/frocwrtdetpepchluna16.py", line 164, in <module>
    getfroc(detp, eps)
  File "/media/omnisky/1F4F46694A801839/zhl/DeepLung-master/evaluationScript/frocwrtdetpepchluna16.py", line 153, in getfroc
    froclist = p.map(getfrocvalue, predannofnamalist)
  File "/home/omnisky/anaconda3/envs/zhl2/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/omnisky/anaconda3/envs/zhl2/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
ValueError: Data is not binary and pos_label is not specified
./annotations/annotations.csv

expecting your reply.

**Comment by wentaozhu** [comment]
Did you train your model?

In the readme, "After training and test are done, use the ./evaluationScript/frocwrtdetpepchluna16.py to validate the epoch used for test.
After that, collect all the 10 folds' prediction, use ./evaluationScript/noduleCADEvaluationLUNA16.py to get the FROC for all 10 folds.
You can directly run noduleCADEvaluationLUNA16.py, and get the performance in the paper."

**Comment by hengliang8** [comment]
thanks for you help, I find the solution. I fill in the wrong path in 'result'.It should be the path of test result.

**Comment by 3learning12340** [comment]
@hengliang8 hello, I meet the same question, but I don't understand your meaning. test results? can you help me to explain it in detail? thank you very much

**Comment by ljk1072911239** [comment]
> thanks for you help, I find the solution. I fill in the wrong path in 'result'.It should be the path of test result.

How can you solve this issue? I encounter it. Thanks.
